import * as React from 'react';

import Head from 'next/head';
import PageContainer from '@/components/PageContainer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContainer>
        <div className="flex flex-col gap-5">
          <h2 className="text-2xl font-semibold text-center">
            Welcome to my Blog
          </h2>
          <p>
            Here you can find articles on various topics and keep updated with
            my reading list.
          </p>
        </div>
      </PageContainer>
    </>
  );
}
