import * as React from 'react';

import Link from 'next/link';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-32 p-4 mx-auto mt-5 bg-slate-50">
        <h1 className="text-3xl font-bold text-center">Anis Dev Diaries</h1>
        <main className="p-2">
          <p>Hello To my personal website, this is still a draft.</p>
          You can take a tour at{' '}
          <Link className="text-cyan-600" href="/blog">
            my blog page
          </Link>
        </main>
      </main>
    </>
  );
}
