import * as React from 'react';

import { GetStaticProps } from 'next';
import Head from 'next/head';
import fs from 'fs';
import { BLOGS_PATH } from '../utils';

type HomeProps = {
  files: string[];
};

export default function Home(props: HomeProps) {
  const { files } = props;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-56 h-32 p-4 mx-auto mt-5 bg-lime-50">
        <h1 className="font-bold text-center">Hello Blog</h1>
        <section className="p-2 bg-black">
          {files.map((file) => (
            <div key={file} className="text-white">
              {file}
            </div>
          ))}
        </section>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const files = await fs.promises.readdir(BLOGS_PATH);

  return {
    props: {
      files,
    },
  };
};
